#!/usr/bin/env python
# -*- coding: utf-8 -*-

import os
import logging
_logger = logging.getLogger(__name__)


CUSTOM = os.environ.get('CUSTOM')
CUSTOM_ODOO = os.path.join(CUSTOM, 'odoo')
if os.path.isdir(CUSTOM_ODOO):
    os.system('pip install --user --no-cache-dir --no-deps -e %s' % CUSTOM_ODOO)
